// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: radar-radar.proto

package proto_radar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadarService_GetSensorState_FullMethodName    = "/radarService.RadarService/GetSensorState"
	RadarService_SetSensorParams_FullMethodName   = "/radarService.RadarService/SetSensorParams"
	RadarService_ManageSensorParam_FullMethodName = "/radarService.RadarService/ManageSensorParam"
	RadarService_ManageLanes_FullMethodName       = "/radarService.RadarService/ManageLanes"
	RadarService_SettingRadar_FullMethodName      = "/radarService.RadarService/SettingRadar"
)

// RadarServiceClient is the client API for RadarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для взаимодействия с радаром
type RadarServiceClient interface {
	// Получение всех параметров радара
	GetSensorState(ctx context.Context, in *GetSensorStateRequest, opts ...grpc.CallOption) (*SensorStateResponse, error)
	// Выставление базовых настроек радара
	SetSensorParams(ctx context.Context, in *SetSensorParamsRequest, opts ...grpc.CallOption) (*SensorStateResponse, error)
	// Выставление/получение конкретного параметра сенсора
	ManageSensorParam(ctx context.Context, in *ManageSensorParamRequest, opts ...grpc.CallOption) (*ManageSensorParamResponse, error)
	// Выставление параметров Lane
	ManageLanes(ctx context.Context, in *ManageLanesRequest, opts ...grpc.CallOption) (*ManageLanesResponse, error)
	// Комплексная настройка радара с полосами
	SettingRadar(ctx context.Context, in *SettingRadarRequest, opts ...grpc.CallOption) (*SettingRadarResponse, error)
}

type radarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRadarServiceClient(cc grpc.ClientConnInterface) RadarServiceClient {
	return &radarServiceClient{cc}
}

func (c *radarServiceClient) GetSensorState(ctx context.Context, in *GetSensorStateRequest, opts ...grpc.CallOption) (*SensorStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorStateResponse)
	err := c.cc.Invoke(ctx, RadarService_GetSensorState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) SetSensorParams(ctx context.Context, in *SetSensorParamsRequest, opts ...grpc.CallOption) (*SensorStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorStateResponse)
	err := c.cc.Invoke(ctx, RadarService_SetSensorParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) ManageSensorParam(ctx context.Context, in *ManageSensorParamRequest, opts ...grpc.CallOption) (*ManageSensorParamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageSensorParamResponse)
	err := c.cc.Invoke(ctx, RadarService_ManageSensorParam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) ManageLanes(ctx context.Context, in *ManageLanesRequest, opts ...grpc.CallOption) (*ManageLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_ManageLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) SettingRadar(ctx context.Context, in *SettingRadarRequest, opts ...grpc.CallOption) (*SettingRadarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingRadarResponse)
	err := c.cc.Invoke(ctx, RadarService_SettingRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadarServiceServer is the server API for RadarService service.
// All implementations must embed UnimplementedRadarServiceServer
// for forward compatibility.
//
// Сервис для взаимодействия с радаром
type RadarServiceServer interface {
	// Получение всех параметров радара
	GetSensorState(context.Context, *GetSensorStateRequest) (*SensorStateResponse, error)
	// Выставление базовых настроек радара
	SetSensorParams(context.Context, *SetSensorParamsRequest) (*SensorStateResponse, error)
	// Выставление/получение конкретного параметра сенсора
	ManageSensorParam(context.Context, *ManageSensorParamRequest) (*ManageSensorParamResponse, error)
	// Выставление параметров Lane
	ManageLanes(context.Context, *ManageLanesRequest) (*ManageLanesResponse, error)
	// Комплексная настройка радара с полосами
	SettingRadar(context.Context, *SettingRadarRequest) (*SettingRadarResponse, error)
	mustEmbedUnimplementedRadarServiceServer()
}

// UnimplementedRadarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadarServiceServer struct{}

func (UnimplementedRadarServiceServer) GetSensorState(context.Context, *GetSensorStateRequest) (*SensorStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorState not implemented")
}
func (UnimplementedRadarServiceServer) SetSensorParams(context.Context, *SetSensorParamsRequest) (*SensorStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSensorParams not implemented")
}
func (UnimplementedRadarServiceServer) ManageSensorParam(context.Context, *ManageSensorParamRequest) (*ManageSensorParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageSensorParam not implemented")
}
func (UnimplementedRadarServiceServer) ManageLanes(context.Context, *ManageLanesRequest) (*ManageLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageLanes not implemented")
}
func (UnimplementedRadarServiceServer) SettingRadar(context.Context, *SettingRadarRequest) (*SettingRadarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettingRadar not implemented")
}
func (UnimplementedRadarServiceServer) mustEmbedUnimplementedRadarServiceServer() {}
func (UnimplementedRadarServiceServer) testEmbeddedByValue()                      {}

// UnsafeRadarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadarServiceServer will
// result in compilation errors.
type UnsafeRadarServiceServer interface {
	mustEmbedUnimplementedRadarServiceServer()
}

func RegisterRadarServiceServer(s grpc.ServiceRegistrar, srv RadarServiceServer) {
	// If the following call pancis, it indicates UnimplementedRadarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadarService_ServiceDesc, srv)
}

func _RadarService_GetSensorState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensorStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetSensorState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetSensorState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetSensorState(ctx, req.(*GetSensorStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_SetSensorParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSensorParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).SetSensorParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_SetSensorParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).SetSensorParams(ctx, req.(*SetSensorParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_ManageSensorParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageSensorParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).ManageSensorParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_ManageSensorParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).ManageSensorParam(ctx, req.(*ManageSensorParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_ManageLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageLanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).ManageLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_ManageLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).ManageLanes(ctx, req.(*ManageLanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_SettingRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingRadarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).SettingRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_SettingRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).SettingRadar(ctx, req.(*SettingRadarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RadarService_ServiceDesc is the grpc.ServiceDesc for RadarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radarService.RadarService",
	HandlerType: (*RadarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSensorState",
			Handler:    _RadarService_GetSensorState_Handler,
		},
		{
			MethodName: "SetSensorParams",
			Handler:    _RadarService_SetSensorParams_Handler,
		},
		{
			MethodName: "ManageSensorParam",
			Handler:    _RadarService_ManageSensorParam_Handler,
		},
		{
			MethodName: "ManageLanes",
			Handler:    _RadarService_ManageLanes_Handler,
		},
		{
			MethodName: "SettingRadar",
			Handler:    _RadarService_SettingRadar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "radar-radar.proto",
}
