// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: radar-radar.proto

package proto_radar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadarService_SetDefaultParamsSensor_FullMethodName = "/radarService.RadarService/SetDefaultParamsSensor"
	RadarService_GetStateSensor_FullMethodName         = "/radarService.RadarService/GetStateSensor"
	RadarService_SetParamSensor_FullMethodName         = "/radarService.RadarService/SetParamSensor"
	RadarService_GetAvailableSensors_FullMethodName    = "/radarService.RadarService/GetAvailableSensors"
)

// RadarServiceClient is the client API for RadarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для взаимодействия с радаром
type RadarServiceClient interface {
	// Выставление базовых настроек радара
	SetDefaultParamsSensor(ctx context.Context, in *SetDefaultParamsSensorRequest, opts ...grpc.CallOption) (*StateSensorResponse, error)
	// Получение всех параметров радара
	GetStateSensor(ctx context.Context, in *GetStateSensorRequest, opts ...grpc.CallOption) (*StateSensorResponse, error)
	// Комплексная настройка радара с полосами
	SetParamSensor(ctx context.Context, in *SetParamSensorRequest, opts ...grpc.CallOption) (*SetParamSensorResponse, error)
	// Получение списка доступных сенсоров
	GetAvailableSensors(ctx context.Context, in *GetAvailableSensorsRequest, opts ...grpc.CallOption) (*GetAvailableSensorsResponse, error)
}

type radarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRadarServiceClient(cc grpc.ClientConnInterface) RadarServiceClient {
	return &radarServiceClient{cc}
}

func (c *radarServiceClient) SetDefaultParamsSensor(ctx context.Context, in *SetDefaultParamsSensorRequest, opts ...grpc.CallOption) (*StateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_SetDefaultParamsSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetStateSensor(ctx context.Context, in *GetStateSensorRequest, opts ...grpc.CallOption) (*StateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_GetStateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) SetParamSensor(ctx context.Context, in *SetParamSensorRequest, opts ...grpc.CallOption) (*SetParamSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetParamSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_SetParamSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAvailableSensors(ctx context.Context, in *GetAvailableSensorsRequest, opts ...grpc.CallOption) (*GetAvailableSensorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableSensorsResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAvailableSensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadarServiceServer is the server API for RadarService service.
// All implementations must embed UnimplementedRadarServiceServer
// for forward compatibility.
//
// Сервис для взаимодействия с радаром
type RadarServiceServer interface {
	// Выставление базовых настроек радара
	SetDefaultParamsSensor(context.Context, *SetDefaultParamsSensorRequest) (*StateSensorResponse, error)
	// Получение всех параметров радара
	GetStateSensor(context.Context, *GetStateSensorRequest) (*StateSensorResponse, error)
	// Комплексная настройка радара с полосами
	SetParamSensor(context.Context, *SetParamSensorRequest) (*SetParamSensorResponse, error)
	// Получение списка доступных сенсоров
	GetAvailableSensors(context.Context, *GetAvailableSensorsRequest) (*GetAvailableSensorsResponse, error)
	mustEmbedUnimplementedRadarServiceServer()
}

// UnimplementedRadarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadarServiceServer struct{}

func (UnimplementedRadarServiceServer) SetDefaultParamsSensor(context.Context, *SetDefaultParamsSensorRequest) (*StateSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultParamsSensor not implemented")
}
func (UnimplementedRadarServiceServer) GetStateSensor(context.Context, *GetStateSensorRequest) (*StateSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStateSensor not implemented")
}
func (UnimplementedRadarServiceServer) SetParamSensor(context.Context, *SetParamSensorRequest) (*SetParamSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetParamSensor not implemented")
}
func (UnimplementedRadarServiceServer) GetAvailableSensors(context.Context, *GetAvailableSensorsRequest) (*GetAvailableSensorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableSensors not implemented")
}
func (UnimplementedRadarServiceServer) mustEmbedUnimplementedRadarServiceServer() {}
func (UnimplementedRadarServiceServer) testEmbeddedByValue()                      {}

// UnsafeRadarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadarServiceServer will
// result in compilation errors.
type UnsafeRadarServiceServer interface {
	mustEmbedUnimplementedRadarServiceServer()
}

func RegisterRadarServiceServer(s grpc.ServiceRegistrar, srv RadarServiceServer) {
	// If the following call pancis, it indicates UnimplementedRadarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadarService_ServiceDesc, srv)
}

func _RadarService_SetDefaultParamsSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultParamsSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).SetDefaultParamsSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_SetDefaultParamsSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).SetDefaultParamsSensor(ctx, req.(*SetDefaultParamsSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetStateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetStateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetStateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetStateSensor(ctx, req.(*GetStateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_SetParamSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetParamSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).SetParamSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_SetParamSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).SetParamSensor(ctx, req.(*SetParamSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAvailableSensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableSensorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAvailableSensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAvailableSensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAvailableSensors(ctx, req.(*GetAvailableSensorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RadarService_ServiceDesc is the grpc.ServiceDesc for RadarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radarService.RadarService",
	HandlerType: (*RadarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDefaultParamsSensor",
			Handler:    _RadarService_SetDefaultParamsSensor_Handler,
		},
		{
			MethodName: "GetStateSensor",
			Handler:    _RadarService_GetStateSensor_Handler,
		},
		{
			MethodName: "SetParamSensor",
			Handler:    _RadarService_SetParamSensor_Handler,
		},
		{
			MethodName: "GetAvailableSensors",
			Handler:    _RadarService_GetAvailableSensors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "radar-radar.proto",
}
