// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: manager-radar.proto

package proto_radar

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadarService_CreateRadar_FullMethodName                   = "/radar.RadarService/CreateRadar"
	RadarService_UpdateRadar_FullMethodName                   = "/radar.RadarService/UpdateRadar"
	RadarService_GetRadar_FullMethodName                      = "/radar.RadarService/GetRadar"
	RadarService_GetAllRadars_FullMethodName                  = "/radar.RadarService/GetAllRadars"
	RadarService_DeleteRadar_FullMethodName                   = "/radar.RadarService/DeleteRadar"
	RadarService_CreateEmptyRadarWithLanes_FullMethodName     = "/radar.RadarService/CreateEmptyRadarWithLanes"
	RadarService_CreateRadarWithLanes_FullMethodName          = "/radar.RadarService/CreateRadarWithLanes"
	RadarService_UpdateRadarWithLanes_FullMethodName          = "/radar.RadarService/UpdateRadarWithLanes"
	RadarService_GetRadarWithLanesForSerial_FullMethodName    = "/radar.RadarService/GetRadarWithLanesForSerial"
	RadarService_GetRadarWithLanesForId_FullMethodName        = "/radar.RadarService/GetRadarWithLanesForId"
	RadarService_GetAllRadarsWithLanes_FullMethodName         = "/radar.RadarService/GetAllRadarsWithLanes"
	RadarService_DeleteRadarWithLanesForSerial_FullMethodName = "/radar.RadarService/DeleteRadarWithLanesForSerial"
	RadarService_DeleteRadarWithLanesForId_FullMethodName     = "/radar.RadarService/DeleteRadarWithLanesForId"
	RadarService_GetTimeZones_FullMethodName                  = "/radar.RadarService/GetTimeZones"
	RadarService_GetRadarModels_FullMethodName                = "/radar.RadarService/GetRadarModels"
	RadarService_GetDirectionTypes_FullMethodName             = "/radar.RadarService/GetDirectionTypes"
	RadarService_GetDevice_FullMethodName                     = "/radar.RadarService/GetDevice"
	RadarService_UpdateDevice_FullMethodName                  = "/radar.RadarService/UpdateDevice"
	RadarService_GetTransportObjectInfo_FullMethodName        = "/radar.RadarService/GetTransportObjectInfo"
	RadarService_GetExportsTypes_FullMethodName               = "/radar.RadarService/GetExportsTypes"
	RadarService_GetExportStatuses_FullMethodName             = "/radar.RadarService/GetExportStatuses"
	RadarService_CreateExport_FullMethodName                  = "/radar.RadarService/CreateExport"
	RadarService_UpdateExport_FullMethodName                  = "/radar.RadarService/UpdateExport"
	RadarService_GetExport_FullMethodName                     = "/radar.RadarService/GetExport"
	RadarService_GetAllExports_FullMethodName                 = "/radar.RadarService/GetAllExports"
	RadarService_DeleteExport_FullMethodName                  = "/radar.RadarService/DeleteExport"
	RadarService_ChangeExportState_FullMethodName             = "/radar.RadarService/ChangeExportState"
	RadarService_GetExportEvents_FullMethodName               = "/radar.RadarService/GetExportEvents"
	RadarService_CreateLane_FullMethodName                    = "/radar.RadarService/CreateLane"
	RadarService_UpdateLane_FullMethodName                    = "/radar.RadarService/UpdateLane"
	RadarService_GetLane_FullMethodName                       = "/radar.RadarService/GetLane"
	RadarService_GetAllLanes_FullMethodName                   = "/radar.RadarService/GetAllLanes"
	RadarService_DeleteLane_FullMethodName                    = "/radar.RadarService/DeleteLane"
	RadarService_CreateSensor_FullMethodName                  = "/radar.RadarService/CreateSensor"
	RadarService_UpdateSensor_FullMethodName                  = "/radar.RadarService/UpdateSensor"
	RadarService_GetAllSensor_FullMethodName                  = "/radar.RadarService/GetAllSensor"
	RadarService_CreateFixationLine_FullMethodName            = "/radar.RadarService/CreateFixationLine"
	RadarService_UpdateFixationLine_FullMethodName            = "/radar.RadarService/UpdateFixationLine"
	RadarService_GetFixationLinesForLane_FullMethodName       = "/radar.RadarService/GetFixationLinesForLane"
	RadarService_GetFixationLinesForRadar_FullMethodName      = "/radar.RadarService/GetFixationLinesForRadar"
	RadarService_DeleteFixationLine_FullMethodName            = "/radar.RadarService/DeleteFixationLine"
)

// RadarServiceClient is the client API for RadarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RadarServiceClient interface {
	// Методы для работы с радарами
	CreateRadar(ctx context.Context, in *CreateRadarRequest, opts ...grpc.CallOption) (*RadarResponse, error)
	UpdateRadar(ctx context.Context, in *UpdateRadarRequest, opts ...grpc.CallOption) (*RadarResponse, error)
	GetRadar(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarResponse, error)
	GetAllRadars(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarsResponse, error)
	DeleteRadar(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarResponse, error)
	// Методы для работы с радарами и полосами
	CreateEmptyRadarWithLanes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarWithLanesResponse, error)
	CreateRadarWithLanes(ctx context.Context, in *CreateRadarWithLanesRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error)
	UpdateRadarWithLanes(ctx context.Context, in *UpdateRadarWithLanesRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error)
	GetRadarWithLanesForSerial(ctx context.Context, in *SerialRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error)
	GetRadarWithLanesForId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error)
	GetAllRadarsWithLanes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarsWithLanesResponse, error)
	DeleteRadarWithLanesForSerial(ctx context.Context, in *SerialRequest, opts ...grpc.CallOption) (*SerialResponse, error)
	DeleteRadarWithLanesForId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SerialResponse, error)
	// Методы для справочников
	GetTimeZones(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TimeZonesResponse, error)
	GetRadarModels(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarModelsResponse, error)
	GetDirectionTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDirectionTypesResponse, error)
	// Методы для работы с устройством (Пуид)
	GetDevice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DeviceResponse, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*DeviceResponse, error)
	// Методы для работы с транспортными объектами
	GetTransportObjectInfo(ctx context.Context, in *GetTransportObjectInfoRequest, opts ...grpc.CallOption) (*GetTransportObjectInfoResponse, error)
	// Методы для работы с экспортами
	GetExportsTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetExportTypesResponse, error)
	GetExportStatuses(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetExportStatusesResponse, error)
	CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	UpdateExport(ctx context.Context, in *UpdateExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	GetExport(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	GetAllExports(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ExportsResponse, error)
	DeleteExport(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExportIdResponse, error)
	ChangeExportState(ctx context.Context, in *ChangeExportStateRequest, opts ...grpc.CallOption) (*ChangeExportStateResponse, error)
	GetExportEvents(ctx context.Context, in *GetExportsEventsRequest, opts ...grpc.CallOption) (*GetExportsEventsResponse, error)
	// Методы для работы с полосами
	CreateLane(ctx context.Context, in *CreateLaneRequest, opts ...grpc.CallOption) (*LaneResponse, error)
	UpdateLane(ctx context.Context, in *UpdateLaneRequest, opts ...grpc.CallOption) (*LaneResponse, error)
	GetLane(ctx context.Context, in *LaneRequest, opts ...grpc.CallOption) (*LaneResponse, error)
	GetAllLanes(ctx context.Context, in *LanesRequest, opts ...grpc.CallOption) (*LanesResponse, error)
	DeleteLane(ctx context.Context, in *LaneRequest, opts ...grpc.CallOption) (*IdResponse, error)
	// Методы для работы с сенсорами
	CreateSensor(ctx context.Context, in *CreateSensorRequest, opts ...grpc.CallOption) (*CreateSensorResponse, error)
	UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error)
	GetAllSensor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllSensorResponse, error)
	// Методы для работы с фиксационными линиями (рубежами)
	CreateFixationLine(ctx context.Context, in *CreateFixationLineRequest, opts ...grpc.CallOption) (*FixationLineResponse, error)
	UpdateFixationLine(ctx context.Context, in *UpdateFixationLineRequest, opts ...grpc.CallOption) (*FixationLineResponse, error)
	GetFixationLinesForLane(ctx context.Context, in *GetFixationLineRequest, opts ...grpc.CallOption) (*FixationLinesForLaneResponse, error)
	GetFixationLinesForRadar(ctx context.Context, in *GetAllFixationLinesRequest, opts ...grpc.CallOption) (*FixationLinesResponse, error)
	DeleteFixationLine(ctx context.Context, in *GetDeleteFixationLineRequest, opts ...grpc.CallOption) (*DeleteFixationLineResponse, error)
}

type radarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRadarServiceClient(cc grpc.ClientConnInterface) RadarServiceClient {
	return &radarServiceClient{cc}
}

func (c *radarServiceClient) CreateRadar(ctx context.Context, in *CreateRadarRequest, opts ...grpc.CallOption) (*RadarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateRadar(ctx context.Context, in *UpdateRadarRequest, opts ...grpc.CallOption) (*RadarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetRadar(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarResponse)
	err := c.cc.Invoke(ctx, RadarService_GetRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAllRadars(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarsResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAllRadars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteRadar(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateEmptyRadarWithLanes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateEmptyRadarWithLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateRadarWithLanes(ctx context.Context, in *CreateRadarWithLanesRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateRadarWithLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateRadarWithLanes(ctx context.Context, in *UpdateRadarWithLanesRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateRadarWithLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetRadarWithLanesForSerial(ctx context.Context, in *SerialRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetRadarWithLanesForSerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetRadarWithLanesForId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*RadarWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetRadarWithLanesForId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAllRadarsWithLanes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarsWithLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarsWithLanesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAllRadarsWithLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteRadarWithLanesForSerial(ctx context.Context, in *SerialRequest, opts ...grpc.CallOption) (*SerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SerialResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteRadarWithLanesForSerial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteRadarWithLanesForId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SerialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SerialResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteRadarWithLanesForId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetTimeZones(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TimeZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeZonesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetTimeZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetRadarModels(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadarModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RadarModelsResponse)
	err := c.cc.Invoke(ctx, RadarService_GetRadarModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetDirectionTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDirectionTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDirectionTypesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetDirectionTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetDevice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, RadarService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*DeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetTransportObjectInfo(ctx context.Context, in *GetTransportObjectInfoRequest, opts ...grpc.CallOption) (*GetTransportObjectInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransportObjectInfoResponse)
	err := c.cc.Invoke(ctx, RadarService_GetTransportObjectInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetExportsTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetExportTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportTypesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetExportsTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetExportStatuses(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetExportStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportStatusesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetExportStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateExport(ctx context.Context, in *UpdateExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetExport(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, RadarService_GetExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAllExports(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ExportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportsResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAllExports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteExport(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExportIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportIdResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) ChangeExportState(ctx context.Context, in *ChangeExportStateRequest, opts ...grpc.CallOption) (*ChangeExportStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeExportStateResponse)
	err := c.cc.Invoke(ctx, RadarService_ChangeExportState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetExportEvents(ctx context.Context, in *GetExportsEventsRequest, opts ...grpc.CallOption) (*GetExportsEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportsEventsResponse)
	err := c.cc.Invoke(ctx, RadarService_GetExportEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateLane(ctx context.Context, in *CreateLaneRequest, opts ...grpc.CallOption) (*LaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaneResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateLane(ctx context.Context, in *UpdateLaneRequest, opts ...grpc.CallOption) (*LaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaneResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetLane(ctx context.Context, in *LaneRequest, opts ...grpc.CallOption) (*LaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaneResponse)
	err := c.cc.Invoke(ctx, RadarService_GetLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAllLanes(ctx context.Context, in *LanesRequest, opts ...grpc.CallOption) (*LanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LanesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAllLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteLane(ctx context.Context, in *LaneRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateSensor(ctx context.Context, in *CreateSensorRequest, opts ...grpc.CallOption) (*CreateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetAllSensor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSensorResponse)
	err := c.cc.Invoke(ctx, RadarService_GetAllSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) CreateFixationLine(ctx context.Context, in *CreateFixationLineRequest, opts ...grpc.CallOption) (*FixationLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FixationLineResponse)
	err := c.cc.Invoke(ctx, RadarService_CreateFixationLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) UpdateFixationLine(ctx context.Context, in *UpdateFixationLineRequest, opts ...grpc.CallOption) (*FixationLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FixationLineResponse)
	err := c.cc.Invoke(ctx, RadarService_UpdateFixationLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetFixationLinesForLane(ctx context.Context, in *GetFixationLineRequest, opts ...grpc.CallOption) (*FixationLinesForLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FixationLinesForLaneResponse)
	err := c.cc.Invoke(ctx, RadarService_GetFixationLinesForLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) GetFixationLinesForRadar(ctx context.Context, in *GetAllFixationLinesRequest, opts ...grpc.CallOption) (*FixationLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FixationLinesResponse)
	err := c.cc.Invoke(ctx, RadarService_GetFixationLinesForRadar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radarServiceClient) DeleteFixationLine(ctx context.Context, in *GetDeleteFixationLineRequest, opts ...grpc.CallOption) (*DeleteFixationLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFixationLineResponse)
	err := c.cc.Invoke(ctx, RadarService_DeleteFixationLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadarServiceServer is the server API for RadarService service.
// All implementations must embed UnimplementedRadarServiceServer
// for forward compatibility.
type RadarServiceServer interface {
	// Методы для работы с радарами
	CreateRadar(context.Context, *CreateRadarRequest) (*RadarResponse, error)
	UpdateRadar(context.Context, *UpdateRadarRequest) (*RadarResponse, error)
	GetRadar(context.Context, *IdRequest) (*RadarResponse, error)
	GetAllRadars(context.Context, *empty.Empty) (*RadarsResponse, error)
	DeleteRadar(context.Context, *IdRequest) (*RadarResponse, error)
	// Методы для работы с радарами и полосами
	CreateEmptyRadarWithLanes(context.Context, *empty.Empty) (*RadarWithLanesResponse, error)
	CreateRadarWithLanes(context.Context, *CreateRadarWithLanesRequest) (*RadarWithLanesResponse, error)
	UpdateRadarWithLanes(context.Context, *UpdateRadarWithLanesRequest) (*RadarWithLanesResponse, error)
	GetRadarWithLanesForSerial(context.Context, *SerialRequest) (*RadarWithLanesResponse, error)
	GetRadarWithLanesForId(context.Context, *IdRequest) (*RadarWithLanesResponse, error)
	GetAllRadarsWithLanes(context.Context, *empty.Empty) (*RadarsWithLanesResponse, error)
	DeleteRadarWithLanesForSerial(context.Context, *SerialRequest) (*SerialResponse, error)
	DeleteRadarWithLanesForId(context.Context, *IdRequest) (*SerialResponse, error)
	// Методы для справочников
	GetTimeZones(context.Context, *empty.Empty) (*TimeZonesResponse, error)
	GetRadarModels(context.Context, *empty.Empty) (*RadarModelsResponse, error)
	GetDirectionTypes(context.Context, *empty.Empty) (*GetDirectionTypesResponse, error)
	// Методы для работы с устройством (Пуид)
	GetDevice(context.Context, *empty.Empty) (*DeviceResponse, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*DeviceResponse, error)
	// Методы для работы с транспортными объектами
	GetTransportObjectInfo(context.Context, *GetTransportObjectInfoRequest) (*GetTransportObjectInfoResponse, error)
	// Методы для работы с экспортами
	GetExportsTypes(context.Context, *empty.Empty) (*GetExportTypesResponse, error)
	GetExportStatuses(context.Context, *empty.Empty) (*GetExportStatusesResponse, error)
	CreateExport(context.Context, *CreateExportRequest) (*ExportResponse, error)
	UpdateExport(context.Context, *UpdateExportRequest) (*ExportResponse, error)
	GetExport(context.Context, *IdRequest) (*ExportResponse, error)
	GetAllExports(context.Context, *empty.Empty) (*ExportsResponse, error)
	DeleteExport(context.Context, *IdRequest) (*ExportIdResponse, error)
	ChangeExportState(context.Context, *ChangeExportStateRequest) (*ChangeExportStateResponse, error)
	GetExportEvents(context.Context, *GetExportsEventsRequest) (*GetExportsEventsResponse, error)
	// Методы для работы с полосами
	CreateLane(context.Context, *CreateLaneRequest) (*LaneResponse, error)
	UpdateLane(context.Context, *UpdateLaneRequest) (*LaneResponse, error)
	GetLane(context.Context, *LaneRequest) (*LaneResponse, error)
	GetAllLanes(context.Context, *LanesRequest) (*LanesResponse, error)
	DeleteLane(context.Context, *LaneRequest) (*IdResponse, error)
	// Методы для работы с сенсорами
	CreateSensor(context.Context, *CreateSensorRequest) (*CreateSensorResponse, error)
	UpdateSensor(context.Context, *UpdateSensorRequest) (*UpdateSensorResponse, error)
	GetAllSensor(context.Context, *empty.Empty) (*GetAllSensorResponse, error)
	// Методы для работы с фиксационными линиями (рубежами)
	CreateFixationLine(context.Context, *CreateFixationLineRequest) (*FixationLineResponse, error)
	UpdateFixationLine(context.Context, *UpdateFixationLineRequest) (*FixationLineResponse, error)
	GetFixationLinesForLane(context.Context, *GetFixationLineRequest) (*FixationLinesForLaneResponse, error)
	GetFixationLinesForRadar(context.Context, *GetAllFixationLinesRequest) (*FixationLinesResponse, error)
	DeleteFixationLine(context.Context, *GetDeleteFixationLineRequest) (*DeleteFixationLineResponse, error)
	mustEmbedUnimplementedRadarServiceServer()
}

// UnimplementedRadarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadarServiceServer struct{}

func (UnimplementedRadarServiceServer) CreateRadar(context.Context, *CreateRadarRequest) (*RadarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRadar not implemented")
}
func (UnimplementedRadarServiceServer) UpdateRadar(context.Context, *UpdateRadarRequest) (*RadarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRadar not implemented")
}
func (UnimplementedRadarServiceServer) GetRadar(context.Context, *IdRequest) (*RadarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadar not implemented")
}
func (UnimplementedRadarServiceServer) GetAllRadars(context.Context, *empty.Empty) (*RadarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRadars not implemented")
}
func (UnimplementedRadarServiceServer) DeleteRadar(context.Context, *IdRequest) (*RadarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRadar not implemented")
}
func (UnimplementedRadarServiceServer) CreateEmptyRadarWithLanes(context.Context, *empty.Empty) (*RadarWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmptyRadarWithLanes not implemented")
}
func (UnimplementedRadarServiceServer) CreateRadarWithLanes(context.Context, *CreateRadarWithLanesRequest) (*RadarWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRadarWithLanes not implemented")
}
func (UnimplementedRadarServiceServer) UpdateRadarWithLanes(context.Context, *UpdateRadarWithLanesRequest) (*RadarWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRadarWithLanes not implemented")
}
func (UnimplementedRadarServiceServer) GetRadarWithLanesForSerial(context.Context, *SerialRequest) (*RadarWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadarWithLanesForSerial not implemented")
}
func (UnimplementedRadarServiceServer) GetRadarWithLanesForId(context.Context, *IdRequest) (*RadarWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadarWithLanesForId not implemented")
}
func (UnimplementedRadarServiceServer) GetAllRadarsWithLanes(context.Context, *empty.Empty) (*RadarsWithLanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRadarsWithLanes not implemented")
}
func (UnimplementedRadarServiceServer) DeleteRadarWithLanesForSerial(context.Context, *SerialRequest) (*SerialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRadarWithLanesForSerial not implemented")
}
func (UnimplementedRadarServiceServer) DeleteRadarWithLanesForId(context.Context, *IdRequest) (*SerialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRadarWithLanesForId not implemented")
}
func (UnimplementedRadarServiceServer) GetTimeZones(context.Context, *empty.Empty) (*TimeZonesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeZones not implemented")
}
func (UnimplementedRadarServiceServer) GetRadarModels(context.Context, *empty.Empty) (*RadarModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadarModels not implemented")
}
func (UnimplementedRadarServiceServer) GetDirectionTypes(context.Context, *empty.Empty) (*GetDirectionTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectionTypes not implemented")
}
func (UnimplementedRadarServiceServer) GetDevice(context.Context, *empty.Empty) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedRadarServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedRadarServiceServer) GetTransportObjectInfo(context.Context, *GetTransportObjectInfoRequest) (*GetTransportObjectInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransportObjectInfo not implemented")
}
func (UnimplementedRadarServiceServer) GetExportsTypes(context.Context, *empty.Empty) (*GetExportTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExportsTypes not implemented")
}
func (UnimplementedRadarServiceServer) GetExportStatuses(context.Context, *empty.Empty) (*GetExportStatusesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExportStatuses not implemented")
}
func (UnimplementedRadarServiceServer) CreateExport(context.Context, *CreateExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExport not implemented")
}
func (UnimplementedRadarServiceServer) UpdateExport(context.Context, *UpdateExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExport not implemented")
}
func (UnimplementedRadarServiceServer) GetExport(context.Context, *IdRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExport not implemented")
}
func (UnimplementedRadarServiceServer) GetAllExports(context.Context, *empty.Empty) (*ExportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllExports not implemented")
}
func (UnimplementedRadarServiceServer) DeleteExport(context.Context, *IdRequest) (*ExportIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExport not implemented")
}
func (UnimplementedRadarServiceServer) ChangeExportState(context.Context, *ChangeExportStateRequest) (*ChangeExportStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeExportState not implemented")
}
func (UnimplementedRadarServiceServer) GetExportEvents(context.Context, *GetExportsEventsRequest) (*GetExportsEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExportEvents not implemented")
}
func (UnimplementedRadarServiceServer) CreateLane(context.Context, *CreateLaneRequest) (*LaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLane not implemented")
}
func (UnimplementedRadarServiceServer) UpdateLane(context.Context, *UpdateLaneRequest) (*LaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLane not implemented")
}
func (UnimplementedRadarServiceServer) GetLane(context.Context, *LaneRequest) (*LaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLane not implemented")
}
func (UnimplementedRadarServiceServer) GetAllLanes(context.Context, *LanesRequest) (*LanesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLanes not implemented")
}
func (UnimplementedRadarServiceServer) DeleteLane(context.Context, *LaneRequest) (*IdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLane not implemented")
}
func (UnimplementedRadarServiceServer) CreateSensor(context.Context, *CreateSensorRequest) (*CreateSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSensor not implemented")
}
func (UnimplementedRadarServiceServer) UpdateSensor(context.Context, *UpdateSensorRequest) (*UpdateSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSensor not implemented")
}
func (UnimplementedRadarServiceServer) GetAllSensor(context.Context, *empty.Empty) (*GetAllSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSensor not implemented")
}
func (UnimplementedRadarServiceServer) CreateFixationLine(context.Context, *CreateFixationLineRequest) (*FixationLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFixationLine not implemented")
}
func (UnimplementedRadarServiceServer) UpdateFixationLine(context.Context, *UpdateFixationLineRequest) (*FixationLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFixationLine not implemented")
}
func (UnimplementedRadarServiceServer) GetFixationLinesForLane(context.Context, *GetFixationLineRequest) (*FixationLinesForLaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFixationLinesForLane not implemented")
}
func (UnimplementedRadarServiceServer) GetFixationLinesForRadar(context.Context, *GetAllFixationLinesRequest) (*FixationLinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFixationLinesForRadar not implemented")
}
func (UnimplementedRadarServiceServer) DeleteFixationLine(context.Context, *GetDeleteFixationLineRequest) (*DeleteFixationLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFixationLine not implemented")
}
func (UnimplementedRadarServiceServer) mustEmbedUnimplementedRadarServiceServer() {}
func (UnimplementedRadarServiceServer) testEmbeddedByValue()                      {}

// UnsafeRadarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadarServiceServer will
// result in compilation errors.
type UnsafeRadarServiceServer interface {
	mustEmbedUnimplementedRadarServiceServer()
}

func RegisterRadarServiceServer(s grpc.ServiceRegistrar, srv RadarServiceServer) {
	// If the following call pancis, it indicates UnimplementedRadarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadarService_ServiceDesc, srv)
}

func _RadarService_CreateRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRadarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateRadar(ctx, req.(*CreateRadarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRadarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateRadar(ctx, req.(*UpdateRadarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetRadar(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAllRadars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAllRadars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAllRadars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAllRadars(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteRadar(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateEmptyRadarWithLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateEmptyRadarWithLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateEmptyRadarWithLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateEmptyRadarWithLanes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateRadarWithLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRadarWithLanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateRadarWithLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateRadarWithLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateRadarWithLanes(ctx, req.(*CreateRadarWithLanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateRadarWithLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRadarWithLanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateRadarWithLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateRadarWithLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateRadarWithLanes(ctx, req.(*UpdateRadarWithLanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetRadarWithLanesForSerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetRadarWithLanesForSerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetRadarWithLanesForSerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetRadarWithLanesForSerial(ctx, req.(*SerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetRadarWithLanesForId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetRadarWithLanesForId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetRadarWithLanesForId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetRadarWithLanesForId(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAllRadarsWithLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAllRadarsWithLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAllRadarsWithLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAllRadarsWithLanes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteRadarWithLanesForSerial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteRadarWithLanesForSerial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteRadarWithLanesForSerial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteRadarWithLanesForSerial(ctx, req.(*SerialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteRadarWithLanesForId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteRadarWithLanesForId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteRadarWithLanesForId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteRadarWithLanesForId(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetTimeZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetTimeZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetTimeZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetTimeZones(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetRadarModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetRadarModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetRadarModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetRadarModels(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetDirectionTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetDirectionTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetDirectionTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetDirectionTypes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetDevice(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetTransportObjectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransportObjectInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetTransportObjectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetTransportObjectInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetTransportObjectInfo(ctx, req.(*GetTransportObjectInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetExportsTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetExportsTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetExportsTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetExportsTypes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetExportStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetExportStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetExportStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetExportStatuses(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateExport(ctx, req.(*CreateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateExport(ctx, req.(*UpdateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetExport(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAllExports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAllExports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAllExports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAllExports(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteExport(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_ChangeExportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeExportStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).ChangeExportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_ChangeExportState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).ChangeExportState(ctx, req.(*ChangeExportStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetExportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportsEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetExportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetExportEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetExportEvents(ctx, req.(*GetExportsEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateLane(ctx, req.(*CreateLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateLane(ctx, req.(*UpdateLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetLane(ctx, req.(*LaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAllLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAllLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAllLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAllLanes(ctx, req.(*LanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteLane(ctx, req.(*LaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateSensor(ctx, req.(*CreateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateSensor(ctx, req.(*UpdateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetAllSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetAllSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetAllSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetAllSensor(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_CreateFixationLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFixationLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).CreateFixationLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_CreateFixationLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).CreateFixationLine(ctx, req.(*CreateFixationLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_UpdateFixationLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFixationLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).UpdateFixationLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_UpdateFixationLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).UpdateFixationLine(ctx, req.(*UpdateFixationLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetFixationLinesForLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFixationLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetFixationLinesForLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetFixationLinesForLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetFixationLinesForLane(ctx, req.(*GetFixationLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_GetFixationLinesForRadar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFixationLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).GetFixationLinesForRadar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_GetFixationLinesForRadar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).GetFixationLinesForRadar(ctx, req.(*GetAllFixationLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadarService_DeleteFixationLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeleteFixationLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadarServiceServer).DeleteFixationLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadarService_DeleteFixationLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadarServiceServer).DeleteFixationLine(ctx, req.(*GetDeleteFixationLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RadarService_ServiceDesc is the grpc.ServiceDesc for RadarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radar.RadarService",
	HandlerType: (*RadarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRadar",
			Handler:    _RadarService_CreateRadar_Handler,
		},
		{
			MethodName: "UpdateRadar",
			Handler:    _RadarService_UpdateRadar_Handler,
		},
		{
			MethodName: "GetRadar",
			Handler:    _RadarService_GetRadar_Handler,
		},
		{
			MethodName: "GetAllRadars",
			Handler:    _RadarService_GetAllRadars_Handler,
		},
		{
			MethodName: "DeleteRadar",
			Handler:    _RadarService_DeleteRadar_Handler,
		},
		{
			MethodName: "CreateEmptyRadarWithLanes",
			Handler:    _RadarService_CreateEmptyRadarWithLanes_Handler,
		},
		{
			MethodName: "CreateRadarWithLanes",
			Handler:    _RadarService_CreateRadarWithLanes_Handler,
		},
		{
			MethodName: "UpdateRadarWithLanes",
			Handler:    _RadarService_UpdateRadarWithLanes_Handler,
		},
		{
			MethodName: "GetRadarWithLanesForSerial",
			Handler:    _RadarService_GetRadarWithLanesForSerial_Handler,
		},
		{
			MethodName: "GetRadarWithLanesForId",
			Handler:    _RadarService_GetRadarWithLanesForId_Handler,
		},
		{
			MethodName: "GetAllRadarsWithLanes",
			Handler:    _RadarService_GetAllRadarsWithLanes_Handler,
		},
		{
			MethodName: "DeleteRadarWithLanesForSerial",
			Handler:    _RadarService_DeleteRadarWithLanesForSerial_Handler,
		},
		{
			MethodName: "DeleteRadarWithLanesForId",
			Handler:    _RadarService_DeleteRadarWithLanesForId_Handler,
		},
		{
			MethodName: "GetTimeZones",
			Handler:    _RadarService_GetTimeZones_Handler,
		},
		{
			MethodName: "GetRadarModels",
			Handler:    _RadarService_GetRadarModels_Handler,
		},
		{
			MethodName: "GetDirectionTypes",
			Handler:    _RadarService_GetDirectionTypes_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _RadarService_GetDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _RadarService_UpdateDevice_Handler,
		},
		{
			MethodName: "GetTransportObjectInfo",
			Handler:    _RadarService_GetTransportObjectInfo_Handler,
		},
		{
			MethodName: "GetExportsTypes",
			Handler:    _RadarService_GetExportsTypes_Handler,
		},
		{
			MethodName: "GetExportStatuses",
			Handler:    _RadarService_GetExportStatuses_Handler,
		},
		{
			MethodName: "CreateExport",
			Handler:    _RadarService_CreateExport_Handler,
		},
		{
			MethodName: "UpdateExport",
			Handler:    _RadarService_UpdateExport_Handler,
		},
		{
			MethodName: "GetExport",
			Handler:    _RadarService_GetExport_Handler,
		},
		{
			MethodName: "GetAllExports",
			Handler:    _RadarService_GetAllExports_Handler,
		},
		{
			MethodName: "DeleteExport",
			Handler:    _RadarService_DeleteExport_Handler,
		},
		{
			MethodName: "ChangeExportState",
			Handler:    _RadarService_ChangeExportState_Handler,
		},
		{
			MethodName: "GetExportEvents",
			Handler:    _RadarService_GetExportEvents_Handler,
		},
		{
			MethodName: "CreateLane",
			Handler:    _RadarService_CreateLane_Handler,
		},
		{
			MethodName: "UpdateLane",
			Handler:    _RadarService_UpdateLane_Handler,
		},
		{
			MethodName: "GetLane",
			Handler:    _RadarService_GetLane_Handler,
		},
		{
			MethodName: "GetAllLanes",
			Handler:    _RadarService_GetAllLanes_Handler,
		},
		{
			MethodName: "DeleteLane",
			Handler:    _RadarService_DeleteLane_Handler,
		},
		{
			MethodName: "CreateSensor",
			Handler:    _RadarService_CreateSensor_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _RadarService_UpdateSensor_Handler,
		},
		{
			MethodName: "GetAllSensor",
			Handler:    _RadarService_GetAllSensor_Handler,
		},
		{
			MethodName: "CreateFixationLine",
			Handler:    _RadarService_CreateFixationLine_Handler,
		},
		{
			MethodName: "UpdateFixationLine",
			Handler:    _RadarService_UpdateFixationLine_Handler,
		},
		{
			MethodName: "GetFixationLinesForLane",
			Handler:    _RadarService_GetFixationLinesForLane_Handler,
		},
		{
			MethodName: "GetFixationLinesForRadar",
			Handler:    _RadarService_GetFixationLinesForRadar_Handler,
		},
		{
			MethodName: "DeleteFixationLine",
			Handler:    _RadarService_DeleteFixationLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager-radar.proto",
}
