// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: manager-radar.proto

package proto_radar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Структура радара
type Radar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Идентификатор радара
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Название радара
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Azimuth       float32                `protobuf:"fixed32,5,opt,name=azimuth,proto3" json:"azimuth,omitempty"`         // Азимут
	Direction     *string                `protobuf:"bytes,6,opt,name=direction,proto3,oneof" json:"direction,omitempty"` // Направление
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`           // Адрес
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`                     // IP-адрес
	Serial        string                 `protobuf:"bytes,9,opt,name=serial,proto3" json:"serial,omitempty"`             // Серийный номер
	Model         string                 `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`              // Модель радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Radar) Reset() {
	*x = Radar{}
	mi := &file_manager_radar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Radar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Radar) ProtoMessage() {}

func (x *Radar) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Radar.ProtoReflect.Descriptor instead.
func (*Radar) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{0}
}

func (x *Radar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Radar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Radar) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Radar) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Radar) GetAzimuth() float32 {
	if x != nil {
		return x.Azimuth
	}
	return 0
}

func (x *Radar) GetDirection() string {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return ""
}

func (x *Radar) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Radar) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Radar) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Radar) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// Ответ сервиса
type RadarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radar         *Radar                 `protobuf:"bytes,1,opt,name=radar,proto3" json:"radar,omitempty"` // Ответ с радаром (при создании или обновлении)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarResponse) Reset() {
	*x = RadarResponse{}
	mi := &file_manager_radar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarResponse) ProtoMessage() {}

func (x *RadarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarResponse.ProtoReflect.Descriptor instead.
func (*RadarResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{1}
}

func (x *RadarResponse) GetRadar() *Radar {
	if x != nil {
		return x.Radar
	}
	return nil
}

// Ответ сервиса
type RadarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radars        []*Radar               `protobuf:"bytes,1,rep,name=radars,proto3" json:"radars,omitempty"` // Ответ с массивом радаров (при получении всех)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarsResponse) Reset() {
	*x = RadarsResponse{}
	mi := &file_manager_radar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarsResponse) ProtoMessage() {}

func (x *RadarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarsResponse.ProtoReflect.Descriptor instead.
func (*RadarsResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{2}
}

func (x *RadarsResponse) GetRadars() []*Radar {
	if x != nil {
		return x.Radars
	}
	return nil
}

// Запрос на создание радара
type CreateRadarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radar         *Radar                 `protobuf:"bytes,1,opt,name=radar,proto3" json:"radar,omitempty"` // Радар для создания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRadarRequest) Reset() {
	*x = CreateRadarRequest{}
	mi := &file_manager_radar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRadarRequest) ProtoMessage() {}

func (x *CreateRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRadarRequest.ProtoReflect.Descriptor instead.
func (*CreateRadarRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRadarRequest) GetRadar() *Radar {
	if x != nil {
		return x.Radar
	}
	return nil
}

// Запрос на обновление радара
type UpdateRadarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // Идентификатор радара
	Radar         *Radar                 `protobuf:"bytes,2,opt,name=radar,proto3" json:"radar,omitempty"` // Обновленные данные радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRadarRequest) Reset() {
	*x = UpdateRadarRequest{}
	mi := &file_manager_radar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRadarRequest) ProtoMessage() {}

func (x *UpdateRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRadarRequest.ProtoReflect.Descriptor instead.
func (*UpdateRadarRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRadarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRadarRequest) GetRadar() *Radar {
	if x != nil {
		return x.Radar
	}
	return nil
}

type RecognitionsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorIds     []string               `protobuf:"bytes,1,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	HeadingFrom   float64                `protobuf:"fixed64,2,opt,name=heading_from,json=headingFrom,proto3" json:"heading_from,omitempty"`
	HeadingTo     float64                `protobuf:"fixed64,3,opt,name=heading_to,json=headingTo,proto3" json:"heading_to,omitempty"`
	LengthFrom    float64                `protobuf:"fixed64,4,opt,name=length_from,json=lengthFrom,proto3" json:"length_from,omitempty"`
	LengthTo      float64                `protobuf:"fixed64,5,opt,name=length_to,json=lengthTo,proto3" json:"length_to,omitempty"`
	SpeedFrom     float64                `protobuf:"fixed64,6,opt,name=speed_from,json=speedFrom,proto3" json:"speed_from,omitempty"`
	SpeedTo       float64                `protobuf:"fixed64,7,opt,name=speed_to,json=speedTo,proto3" json:"speed_to,omitempty"`
	DateFrom      int64                  `protobuf:"varint,8,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        int64                  `protobuf:"varint,9,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Sorting       string                 `protobuf:"bytes,10,opt,name=sorting,proto3" json:"sorting,omitempty"` // "asc" or "desc"
	SortingColumn string                 `protobuf:"bytes,11,opt,name=sorting_column,json=sortingColumn,proto3" json:"sorting_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognitionsFilter) Reset() {
	*x = RecognitionsFilter{}
	mi := &file_manager_radar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionsFilter) ProtoMessage() {}

func (x *RecognitionsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionsFilter.ProtoReflect.Descriptor instead.
func (*RecognitionsFilter) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{5}
}

func (x *RecognitionsFilter) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *RecognitionsFilter) GetHeadingFrom() float64 {
	if x != nil {
		return x.HeadingFrom
	}
	return 0
}

func (x *RecognitionsFilter) GetHeadingTo() float64 {
	if x != nil {
		return x.HeadingTo
	}
	return 0
}

func (x *RecognitionsFilter) GetLengthFrom() float64 {
	if x != nil {
		return x.LengthFrom
	}
	return 0
}

func (x *RecognitionsFilter) GetLengthTo() float64 {
	if x != nil {
		return x.LengthTo
	}
	return 0
}

func (x *RecognitionsFilter) GetSpeedFrom() float64 {
	if x != nil {
		return x.SpeedFrom
	}
	return 0
}

func (x *RecognitionsFilter) GetSpeedTo() float64 {
	if x != nil {
		return x.SpeedTo
	}
	return 0
}

func (x *RecognitionsFilter) GetDateFrom() int64 {
	if x != nil {
		return x.DateFrom
	}
	return 0
}

func (x *RecognitionsFilter) GetDateTo() int64 {
	if x != nil {
		return x.DateTo
	}
	return 0
}

func (x *RecognitionsFilter) GetSorting() string {
	if x != nil {
		return x.Sorting
	}
	return ""
}

func (x *RecognitionsFilter) GetSortingColumn() string {
	if x != nil {
		return x.SortingColumn
	}
	return ""
}

type GetTransportObjectInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         // номер страницы
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // кол-во объектов на странице
	Filter        *RecognitionsFilter    `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransportObjectInfoRequest) Reset() {
	*x = GetTransportObjectInfoRequest{}
	mi := &file_manager_radar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportObjectInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportObjectInfoRequest) ProtoMessage() {}

func (x *GetTransportObjectInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportObjectInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTransportObjectInfoRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransportObjectInfoRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransportObjectInfoRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransportObjectInfoRequest) GetFilter() *RecognitionsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type TransportObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SensorId      string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	OriginId      string                 `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Coordinates   []byte                 `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"` // JSON-encoded координаты
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	Length        float64                `protobuf:"fixed64,8,opt,name=length,proto3" json:"length,omitempty"`
	Date          int64                  `protobuf:"varint,9,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportObjectInfo) Reset() {
	*x = TransportObjectInfo{}
	mi := &file_manager_radar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportObjectInfo) ProtoMessage() {}

func (x *TransportObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportObjectInfo.ProtoReflect.Descriptor instead.
func (*TransportObjectInfo) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{7}
}

func (x *TransportObjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransportObjectInfo) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *TransportObjectInfo) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *TransportObjectInfo) GetCoordinates() []byte {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *TransportObjectInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TransportObjectInfo) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TransportObjectInfo) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *TransportObjectInfo) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TransportObjectInfo) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *TransportObjectInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTransportObjectInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TransportObjectInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int64                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransportObjectInfoResponse) Reset() {
	*x = GetTransportObjectInfoResponse{}
	mi := &file_manager_radar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportObjectInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportObjectInfoResponse) ProtoMessage() {}

func (x *GetTransportObjectInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportObjectInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTransportObjectInfoResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransportObjectInfoResponse) GetData() []*TransportObjectInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTransportObjectInfoResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransportObjectInfoResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransportObjectInfoResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

// Запрос на получение информации о радаре по ID
type GetRadarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRadarRequest) Reset() {
	*x = GetRadarRequest{}
	mi := &file_manager_radar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarRequest) ProtoMessage() {}

func (x *GetRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarRequest.ProtoReflect.Descriptor instead.
func (*GetRadarRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{9}
}

func (x *GetRadarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на удаление радара по ID
type DeleteRadarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRadarRequest) Reset() {
	*x = DeleteRadarRequest{}
	mi := &file_manager_radar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRadarRequest) ProtoMessage() {}

func (x *DeleteRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRadarRequest.ProtoReflect.Descriptor instead.
func (*DeleteRadarRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRadarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с временными зонами
type TimeZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeZones     []*TimeZone            `protobuf:"bytes,1,rep,name=time_zones,json=timeZones,proto3" json:"time_zones,omitempty"` // Список временных зон
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeZonesResponse) Reset() {
	*x = TimeZonesResponse{}
	mi := &file_manager_radar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeZonesResponse) ProtoMessage() {}

func (x *TimeZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeZonesResponse.ProtoReflect.Descriptor instead.
func (*TimeZonesResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{11}
}

func (x *TimeZonesResponse) GetTimeZones() []*TimeZone {
	if x != nil {
		return x.TimeZones
	}
	return nil
}

type TimeZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	TimeZone      string                 `protobuf:"bytes,3,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeZone) Reset() {
	*x = TimeZone{}
	mi := &file_manager_radar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeZone) ProtoMessage() {}

func (x *TimeZone) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeZone.ProtoReflect.Descriptor instead.
func (*TimeZone) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{12}
}

func (x *TimeZone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeZone) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *TimeZone) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

// Ответ с моделями радара
type RadarModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*RadarModel          `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // Список моделей радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarModelsResponse) Reset() {
	*x = RadarModelsResponse{}
	mi := &file_manager_radar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarModelsResponse) ProtoMessage() {}

func (x *RadarModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarModelsResponse.ProtoReflect.Descriptor instead.
func (*RadarModelsResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{13}
}

func (x *RadarModelsResponse) GetModels() []*RadarModel {
	if x != nil {
		return x.Models
	}
	return nil
}

// Структура модели радара
type RadarModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Идентификатор модели
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`                          // Алиас модели
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // Название модели
	Manufacturer  string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`            // Производитель модели
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarModel) Reset() {
	*x = RadarModel{}
	mi := &file_manager_radar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarModel) ProtoMessage() {}

func (x *RadarModel) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarModel.ProtoReflect.Descriptor instead.
func (*RadarModel) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{14}
}

func (x *RadarModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RadarModel) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RadarModel) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RadarModel) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // Идентификатор Пуида
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // Название Пуида
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                     // Адрес
	Lat            float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`                                           // Широта
	Lon            float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`                                           // Долгота
	Serial         string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`                                       // Серийный номер
	ProductionDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=production_date,json=productionDate,proto3" json:"production_date,omitempty"` // Дата производства
	Note           *string                `protobuf:"bytes,8,opt,name=note,proto3,oneof" json:"note,omitempty"`                                     // Примечание
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_manager_radar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{15}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Device) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Device) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Device) GetProductionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ProductionDate
	}
	return nil
}

func (x *Device) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type DeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
	mi := &file_manager_radar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResponse.ProtoReflect.Descriptor instead.
func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_manager_radar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDeviceRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type ExportTypeParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTypeParam) Reset() {
	*x = ExportTypeParam{}
	mi := &file_manager_radar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTypeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTypeParam) ProtoMessage() {}

func (x *ExportTypeParam) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTypeParam.ProtoReflect.Descriptor instead.
func (*ExportTypeParam) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{18}
}

func (x *ExportTypeParam) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type ExportType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Parameters    []*ExportTypeParam     `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportType) Reset() {
	*x = ExportType{}
	mi := &file_manager_radar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportType) ProtoMessage() {}

func (x *ExportType) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportType.ProtoReflect.Descriptor instead.
func (*ExportType) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{19}
}

func (x *ExportType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportType) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ExportType) GetParameters() []*ExportTypeParam {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetExportTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*ExportType          `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportTypesResponse) Reset() {
	*x = GetExportTypesResponse{}
	mi := &file_manager_radar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportTypesResponse) ProtoMessage() {}

func (x *GetExportTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportTypesResponse.ProtoReflect.Descriptor instead.
func (*GetExportTypesResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{20}
}

func (x *GetExportTypesResponse) GetTypes() []*ExportType {
	if x != nil {
		return x.Types
	}
	return nil
}

type ExportStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportStatus) Reset() {
	*x = ExportStatus{}
	mi := &file_manager_radar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportStatus) ProtoMessage() {}

func (x *ExportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportStatus.ProtoReflect.Descriptor instead.
func (*ExportStatus) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{21}
}

func (x *ExportStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportStatus) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetExportStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ExportStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportStatusesResponse) Reset() {
	*x = GetExportStatusesResponse{}
	mi := &file_manager_radar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportStatusesResponse) ProtoMessage() {}

func (x *GetExportStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetExportStatusesResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{22}
}

func (x *GetExportStatusesResponse) GetStatuses() []*ExportStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// Структура экспорта
type Export struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExportType    string                 `protobuf:"bytes,3,opt,name=export_type,json=exportType,proto3" json:"export_type,omitempty"`
	Interval      int32                  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Host          *string                `protobuf:"bytes,5,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Port          *string                `protobuf:"bytes,6,opt,name=port,proto3,oneof" json:"port,omitempty"`
	Login         *string                `protobuf:"bytes,7,opt,name=login,proto3,oneof" json:"login,omitempty"`
	Password      *string                `protobuf:"bytes,8,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Queue         *string                `protobuf:"bytes,9,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	VirtualHost   *string                `protobuf:"bytes,10,opt,name=virtual_host,json=virtualHost,proto3,oneof" json:"virtual_host,omitempty"`
	RoutingKey    *string                `protobuf:"bytes,11,opt,name=routing_key,json=routingKey,proto3,oneof" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Export) Reset() {
	*x = Export{}
	mi := &file_manager_radar_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Export) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Export) ProtoMessage() {}

func (x *Export) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Export.ProtoReflect.Descriptor instead.
func (*Export) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{23}
}

func (x *Export) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Export) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Export) GetExportType() string {
	if x != nil {
		return x.ExportType
	}
	return ""
}

func (x *Export) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Export) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *Export) GetPort() string {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return ""
}

func (x *Export) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *Export) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Export) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

func (x *Export) GetVirtualHost() string {
	if x != nil && x.VirtualHost != nil {
		return *x.VirtualHost
	}
	return ""
}

func (x *Export) GetRoutingKey() string {
	if x != nil && x.RoutingKey != nil {
		return *x.RoutingKey
	}
	return ""
}

type ListExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExportType    string                 `protobuf:"bytes,3,opt,name=export_type,json=exportType,proto3" json:"export_type,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	ExportOn      bool                   `protobuf:"varint,6,opt,name=export_on,json=exportOn,proto3" json:"export_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExport) Reset() {
	*x = ListExport{}
	mi := &file_manager_radar_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExport) ProtoMessage() {}

func (x *ListExport) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExport.ProtoReflect.Descriptor instead.
func (*ListExport) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{24}
}

func (x *ListExport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListExport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListExport) GetExportType() string {
	if x != nil {
		return x.ExportType
	}
	return ""
}

func (x *ListExport) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ListExport) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ListExport) GetExportOn() bool {
	if x != nil {
		return x.ExportOn
	}
	return false
}

type ExportEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExportId         string                 `protobuf:"bytes,2,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	Date             int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ExportStartDate  int64                  `protobuf:"varint,5,opt,name=export_start_date,json=exportStartDate,proto3" json:"export_start_date,omitempty"`
	ExportFinishDate int64                  `protobuf:"varint,6,opt,name=export_finish_date,json=exportFinishDate,proto3" json:"export_finish_date,omitempty"`
	ExportStatus     string                 `protobuf:"bytes,7,opt,name=export_status,json=exportStatus,proto3" json:"export_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExportEvent) Reset() {
	*x = ExportEvent{}
	mi := &file_manager_radar_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEvent) ProtoMessage() {}

func (x *ExportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEvent.ProtoReflect.Descriptor instead.
func (*ExportEvent) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{25}
}

func (x *ExportEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportEvent) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *ExportEvent) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ExportEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportEvent) GetExportStartDate() int64 {
	if x != nil {
		return x.ExportStartDate
	}
	return 0
}

func (x *ExportEvent) GetExportFinishDate() int64 {
	if x != nil {
		return x.ExportFinishDate
	}
	return 0
}

func (x *ExportEvent) GetExportStatus() string {
	if x != nil {
		return x.ExportStatus
	}
	return ""
}

type ExportsEventsFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExportIds           []string               `protobuf:"bytes,1,rep,name=export_ids,json=exportIds,proto3" json:"export_ids,omitempty"`
	Statuses            []string               `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	ExportStartDateFrom int64                  `protobuf:"varint,3,opt,name=export_start_date_from,json=exportStartDateFrom,proto3" json:"export_start_date_from,omitempty"`
	ExportStartDateTo   int64                  `protobuf:"varint,4,opt,name=export_start_date_to,json=exportStartDateTo,proto3" json:"export_start_date_to,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExportsEventsFilter) Reset() {
	*x = ExportsEventsFilter{}
	mi := &file_manager_radar_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportsEventsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportsEventsFilter) ProtoMessage() {}

func (x *ExportsEventsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportsEventsFilter.ProtoReflect.Descriptor instead.
func (*ExportsEventsFilter) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{26}
}

func (x *ExportsEventsFilter) GetExportIds() []string {
	if x != nil {
		return x.ExportIds
	}
	return nil
}

func (x *ExportsEventsFilter) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ExportsEventsFilter) GetExportStartDateFrom() int64 {
	if x != nil {
		return x.ExportStartDateFrom
	}
	return 0
}

func (x *ExportsEventsFilter) GetExportStartDateTo() int64 {
	if x != nil {
		return x.ExportStartDateTo
	}
	return 0
}

type GetExportsEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         // номер страницы
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // кол-во объектов на странице
	Filter        *ExportsEventsFilter   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportsEventsRequest) Reset() {
	*x = GetExportsEventsRequest{}
	mi := &file_manager_radar_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportsEventsRequest) ProtoMessage() {}

func (x *GetExportsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportsEventsRequest.ProtoReflect.Descriptor instead.
func (*GetExportsEventsRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{27}
}

func (x *GetExportsEventsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExportsEventsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetExportsEventsRequest) GetFilter() *ExportsEventsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Ответ сервиса
type GetExportsEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportsEvents []*ExportEvent         `protobuf:"bytes,1,rep,name=exportsEvents,proto3" json:"exportsEvents,omitempty"` // Ответ с экспортом (при создании или обновлении)
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int64                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportsEventsResponse) Reset() {
	*x = GetExportsEventsResponse{}
	mi := &file_manager_radar_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportsEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportsEventsResponse) ProtoMessage() {}

func (x *GetExportsEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportsEventsResponse.ProtoReflect.Descriptor instead.
func (*GetExportsEventsResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{28}
}

func (x *GetExportsEventsResponse) GetExportsEvents() []*ExportEvent {
	if x != nil {
		return x.ExportsEvents
	}
	return nil
}

func (x *GetExportsEventsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExportsEventsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetExportsEventsResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

// Ответ сервиса
type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Export        *Export                `protobuf:"bytes,1,opt,name=export,proto3" json:"export,omitempty"` // Ответ с экспортом (при создании или обновлении)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_manager_radar_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{29}
}

func (x *ExportResponse) GetExport() *Export {
	if x != nil {
		return x.Export
	}
	return nil
}

// Ответ сервиса
type ExportIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=exportId,proto3" json:"exportId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportIdResponse) Reset() {
	*x = ExportIdResponse{}
	mi := &file_manager_radar_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportIdResponse) ProtoMessage() {}

func (x *ExportIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportIdResponse.ProtoReflect.Descriptor instead.
func (*ExportIdResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{30}
}

func (x *ExportIdResponse) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

// Ответ сервиса
type ExportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exports       []*ListExport          `protobuf:"bytes,1,rep,name=exports,proto3" json:"exports,omitempty"` // Ответ с массивом экспортов (при получении всех)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportsResponse) Reset() {
	*x = ExportsResponse{}
	mi := &file_manager_radar_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportsResponse) ProtoMessage() {}

func (x *ExportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportsResponse.ProtoReflect.Descriptor instead.
func (*ExportsResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{31}
}

func (x *ExportsResponse) GetExports() []*ListExport {
	if x != nil {
		return x.Exports
	}
	return nil
}

// Запрос на создание экспорта
type CreateExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Export        *Export                `protobuf:"bytes,1,opt,name=export,proto3" json:"export,omitempty"` // экспорт для создания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportRequest) Reset() {
	*x = CreateExportRequest{}
	mi := &file_manager_radar_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportRequest) ProtoMessage() {}

func (x *CreateExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportRequest.ProtoReflect.Descriptor instead.
func (*CreateExportRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{32}
}

func (x *CreateExportRequest) GetExport() *Export {
	if x != nil {
		return x.Export
	}
	return nil
}

// Запрос на обновление экспорта
type UpdateExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Export        *Export                `protobuf:"bytes,1,opt,name=export,proto3" json:"export,omitempty"` // Обновленные данные экспорта
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExportRequest) Reset() {
	*x = UpdateExportRequest{}
	mi := &file_manager_radar_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExportRequest) ProtoMessage() {}

func (x *UpdateExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExportRequest.ProtoReflect.Descriptor instead.
func (*UpdateExportRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateExportRequest) GetExport() *Export {
	if x != nil {
		return x.Export
	}
	return nil
}

// Запрос на получение информации о радаре по ID
type GetExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportRequest) Reset() {
	*x = GetExportRequest{}
	mi := &file_manager_radar_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportRequest) ProtoMessage() {}

func (x *GetExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportRequest.ProtoReflect.Descriptor instead.
func (*GetExportRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{34}
}

func (x *GetExportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на удаление радара по ID
type DeleteExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportRequest) Reset() {
	*x = DeleteExportRequest{}
	mi := &file_manager_radar_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportRequest) ProtoMessage() {}

func (x *DeleteExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportRequest.ProtoReflect.Descriptor instead.
func (*DeleteExportRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteExportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на вкл/выкл радара по ID
type ChangeExportStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	ExportOn      bool                   `protobuf:"varint,2,opt,name=export_on,json=exportOn,proto3" json:"export_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeExportStateRequest) Reset() {
	*x = ChangeExportStateRequest{}
	mi := &file_manager_radar_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeExportStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeExportStateRequest) ProtoMessage() {}

func (x *ChangeExportStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeExportStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeExportStateRequest) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{36}
}

func (x *ChangeExportStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeExportStateRequest) GetExportOn() bool {
	if x != nil {
		return x.ExportOn
	}
	return false
}

type ChangeExportStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Идентификатор радара
	ExportOn      bool                   `protobuf:"varint,2,opt,name=export_on,json=exportOn,proto3" json:"export_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeExportStateResponse) Reset() {
	*x = ChangeExportStateResponse{}
	mi := &file_manager_radar_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeExportStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeExportStateResponse) ProtoMessage() {}

func (x *ChangeExportStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_radar_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeExportStateResponse.ProtoReflect.Descriptor instead.
func (*ChangeExportStateResponse) Descriptor() ([]byte, []int) {
	return file_manager_radar_proto_rawDescGZIP(), []int{37}
}

func (x *ChangeExportStateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeExportStateResponse) GetExportOn() bool {
	if x != nil {
		return x.ExportOn
	}
	return false
}

var File_manager_radar_proto protoreflect.FileDescriptor

const file_manager_radar_proto_rawDesc = "" +
	"\n" +
	"\x13manager-radar.proto\x12\x05radar\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\x05Radar\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x18\n" +
	"\aazimuth\x18\x05 \x01(\x02R\aazimuth\x12!\n" +
	"\tdirection\x18\x06 \x01(\tH\x00R\tdirection\x88\x01\x01\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x16\n" +
	"\x06serial\x18\t \x01(\tR\x06serial\x12\x14\n" +
	"\x05model\x18\n" +
	" \x01(\tR\x05modelB\f\n" +
	"\n" +
	"_direction\"3\n" +
	"\rRadarResponse\x12\"\n" +
	"\x05radar\x18\x01 \x01(\v2\f.radar.RadarR\x05radar\"6\n" +
	"\x0eRadarsResponse\x12$\n" +
	"\x06radars\x18\x01 \x03(\v2\f.radar.RadarR\x06radars\"8\n" +
	"\x12CreateRadarRequest\x12\"\n" +
	"\x05radar\x18\x01 \x01(\v2\f.radar.RadarR\x05radar\"H\n" +
	"\x12UpdateRadarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x05radar\x18\x02 \x01(\v2\f.radar.RadarR\x05radar\"\xe4\x02\n" +
	"\x12RecognitionsFilter\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x01 \x03(\tR\tsensorIds\x12!\n" +
	"\fheading_from\x18\x02 \x01(\x01R\vheadingFrom\x12\x1d\n" +
	"\n" +
	"heading_to\x18\x03 \x01(\x01R\theadingTo\x12\x1f\n" +
	"\vlength_from\x18\x04 \x01(\x01R\n" +
	"lengthFrom\x12\x1b\n" +
	"\tlength_to\x18\x05 \x01(\x01R\blengthTo\x12\x1d\n" +
	"\n" +
	"speed_from\x18\x06 \x01(\x01R\tspeedFrom\x12\x19\n" +
	"\bspeed_to\x18\a \x01(\x01R\aspeedTo\x12\x1b\n" +
	"\tdate_from\x18\b \x01(\x03R\bdateFrom\x12\x17\n" +
	"\adate_to\x18\t \x01(\x03R\x06dateTo\x12\x18\n" +
	"\asorting\x18\n" +
	" \x01(\tR\asorting\x12%\n" +
	"\x0esorting_column\x18\v \x01(\tR\rsortingColumn\"\x82\x01\n" +
	"\x1dGetTransportObjectInfoRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x121\n" +
	"\x06filter\x18\x03 \x01(\v2\x19.radar.RecognitionsFilterR\x06filter\"\xae\x02\n" +
	"\x13TransportObjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12\x1b\n" +
	"\torigin_id\x18\x03 \x01(\tR\boriginId\x12 \n" +
	"\vcoordinates\x18\x04 \x01(\fR\vcoordinates\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\a \x01(\x01R\aheading\x12\x16\n" +
	"\x06length\x18\b \x01(\x01R\x06length\x12\x12\n" +
	"\x04date\x18\t \x01(\x03R\x04date\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa2\x01\n" +
	"\x1eGetTransportObjectInfoResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.radar.TransportObjectInfoR\x04data\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x03R\n" +
	"totalItems\"!\n" +
	"\x0fGetRadarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteRadarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x11TimeZonesResponse\x12.\n" +
	"\n" +
	"time_zones\x18\x01 \x03(\v2\x0f.radar.TimeZoneR\ttimeZones\"T\n" +
	"\bTimeZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1b\n" +
	"\ttime_zone\x18\x03 \x01(\tR\btimeZone\"@\n" +
	"\x13RadarModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.radar.RadarModelR\x06models\"u\n" +
	"\n" +
	"RadarModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\"\xe9\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12C\n" +
	"\x0fproduction_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eproductionDate\x12\x17\n" +
	"\x04note\x18\b \x01(\tH\x00R\x04note\x88\x01\x01B\a\n" +
	"\x05_note\"7\n" +
	"\x0eDeviceResponse\x12%\n" +
	"\x06device\x18\x01 \x01(\v2\r.radar.DeviceR\x06device\"<\n" +
	"\x13UpdateDeviceRequest\x12%\n" +
	"\x06device\x18\x01 \x01(\v2\r.radar.DeviceR\x06device\"'\n" +
	"\x0fExportTypeParam\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\"q\n" +
	"\n" +
	"ExportType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x126\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\x16.radar.ExportTypeParamR\n" +
	"parameters\"A\n" +
	"\x16GetExportTypesResponse\x12'\n" +
	"\x05types\x18\x01 \x03(\v2\x11.radar.ExportTypeR\x05types\";\n" +
	"\fExportStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"L\n" +
	"\x19GetExportStatusesResponse\x12/\n" +
	"\bstatuses\x18\x01 \x03(\v2\x13.radar.ExportStatusR\bstatuses\"\x94\x03\n" +
	"\x06Export\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vexport_type\x18\x03 \x01(\tR\n" +
	"exportType\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x05R\binterval\x12\x17\n" +
	"\x04host\x18\x05 \x01(\tH\x00R\x04host\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x06 \x01(\tH\x01R\x04port\x88\x01\x01\x12\x19\n" +
	"\x05login\x18\a \x01(\tH\x02R\x05login\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\b \x01(\tH\x03R\bpassword\x88\x01\x01\x12\x19\n" +
	"\x05queue\x18\t \x01(\tH\x04R\x05queue\x88\x01\x01\x12&\n" +
	"\fvirtual_host\x18\n" +
	" \x01(\tH\x05R\vvirtualHost\x88\x01\x01\x12$\n" +
	"\vrouting_key\x18\v \x01(\tH\x06R\n" +
	"routingKey\x88\x01\x01B\a\n" +
	"\x05_hostB\a\n" +
	"\x05_portB\b\n" +
	"\x06_loginB\v\n" +
	"\t_passwordB\b\n" +
	"\x06_queueB\x0f\n" +
	"\r_virtual_hostB\x0e\n" +
	"\f_routing_key\"\x96\x01\n" +
	"\n" +
	"ListExport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vexport_type\x18\x03 \x01(\tR\n" +
	"exportType\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\tR\x04port\x12\x1b\n" +
	"\texport_on\x18\x06 \x01(\bR\bexportOn\"\xe1\x01\n" +
	"\vExportEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\texport_id\x18\x02 \x01(\tR\bexportId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12*\n" +
	"\x11export_start_date\x18\x05 \x01(\x03R\x0fexportStartDate\x12,\n" +
	"\x12export_finish_date\x18\x06 \x01(\x03R\x10exportFinishDate\x12#\n" +
	"\rexport_status\x18\a \x01(\tR\fexportStatus\"\xb6\x01\n" +
	"\x13ExportsEventsFilter\x12\x1d\n" +
	"\n" +
	"export_ids\x18\x01 \x03(\tR\texportIds\x12\x1a\n" +
	"\bstatuses\x18\x02 \x03(\tR\bstatuses\x123\n" +
	"\x16export_start_date_from\x18\x03 \x01(\x03R\x13exportStartDateFrom\x12/\n" +
	"\x14export_start_date_to\x18\x04 \x01(\x03R\x11exportStartDateTo\"}\n" +
	"\x17GetExportsEventsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x122\n" +
	"\x06filter\x18\x03 \x01(\v2\x1a.radar.ExportsEventsFilterR\x06filter\"\xa6\x01\n" +
	"\x18GetExportsEventsResponse\x128\n" +
	"\rexportsEvents\x18\x01 \x03(\v2\x12.radar.ExportEventR\rexportsEvents\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x03R\n" +
	"totalItems\"7\n" +
	"\x0eExportResponse\x12%\n" +
	"\x06export\x18\x01 \x01(\v2\r.radar.ExportR\x06export\".\n" +
	"\x10ExportIdResponse\x12\x1a\n" +
	"\bexportId\x18\x01 \x01(\tR\bexportId\">\n" +
	"\x0fExportsResponse\x12+\n" +
	"\aexports\x18\x01 \x03(\v2\x11.radar.ListExportR\aexports\"<\n" +
	"\x13CreateExportRequest\x12%\n" +
	"\x06export\x18\x01 \x01(\v2\r.radar.ExportR\x06export\"<\n" +
	"\x13UpdateExportRequest\x12%\n" +
	"\x06export\x18\x01 \x01(\v2\r.radar.ExportR\x06export\"\"\n" +
	"\x10GetExportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteExportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x18ChangeExportStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\texport_on\x18\x02 \x01(\bR\bexportOn\"H\n" +
	"\x19ChangeExportStateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\texport_on\x18\x02 \x01(\bR\bexportOn2\xc3\n" +
	"\n" +
	"\fRadarService\x12>\n" +
	"\vCreateRadar\x12\x19.radar.CreateRadarRequest\x1a\x14.radar.RadarResponse\x12>\n" +
	"\vUpdateRadar\x12\x19.radar.UpdateRadarRequest\x1a\x14.radar.RadarResponse\x128\n" +
	"\bGetRadar\x12\x16.radar.GetRadarRequest\x1a\x14.radar.RadarResponse\x12=\n" +
	"\fGetAllRadars\x12\x16.google.protobuf.Empty\x1a\x15.radar.RadarsResponse\x12>\n" +
	"\vDeleteRadar\x12\x19.radar.DeleteRadarRequest\x1a\x14.radar.RadarResponse\x12@\n" +
	"\fGetTimeZones\x12\x16.google.protobuf.Empty\x1a\x18.radar.TimeZonesResponse\x12D\n" +
	"\x0eGetRadarModels\x12\x16.google.protobuf.Empty\x1a\x1a.radar.RadarModelsResponse\x12:\n" +
	"\tGetDevice\x12\x16.google.protobuf.Empty\x1a\x15.radar.DeviceResponse\x12A\n" +
	"\fUpdateDevice\x12\x1a.radar.UpdateDeviceRequest\x1a\x15.radar.DeviceResponse\x12e\n" +
	"\x16GetTransportObjectInfo\x12$.radar.GetTransportObjectInfoRequest\x1a%.radar.GetTransportObjectInfoResponse\x12H\n" +
	"\x0fGetExportsTypes\x12\x16.google.protobuf.Empty\x1a\x1d.radar.GetExportTypesResponse\x12M\n" +
	"\x11GetExportStatuses\x12\x16.google.protobuf.Empty\x1a .radar.GetExportStatusesResponse\x12A\n" +
	"\fCreateExport\x12\x1a.radar.CreateExportRequest\x1a\x15.radar.ExportResponse\x12A\n" +
	"\fUpdateExport\x12\x1a.radar.UpdateExportRequest\x1a\x15.radar.ExportResponse\x12;\n" +
	"\tGetExport\x12\x17.radar.GetExportRequest\x1a\x15.radar.ExportResponse\x12?\n" +
	"\rGetAllExports\x12\x16.google.protobuf.Empty\x1a\x16.radar.ExportsResponse\x12C\n" +
	"\fDeleteExport\x12\x1a.radar.DeleteExportRequest\x1a\x17.radar.ExportIdResponse\x12V\n" +
	"\x11ChangeExportState\x12\x1f.radar.ChangeExportStateRequest\x1a .radar.ChangeExportStateResponse\x12R\n" +
	"\x0fGetExportEvents\x12\x1e.radar.GetExportsEventsRequest\x1a\x1f.radar.GetExportsEventsResponseB!Z\x1fgl.npo-its.ru/radar/proto-radarb\x06proto3"

var (
	file_manager_radar_proto_rawDescOnce sync.Once
	file_manager_radar_proto_rawDescData []byte
)

func file_manager_radar_proto_rawDescGZIP() []byte {
	file_manager_radar_proto_rawDescOnce.Do(func() {
		file_manager_radar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_radar_proto_rawDesc), len(file_manager_radar_proto_rawDesc)))
	})
	return file_manager_radar_proto_rawDescData
}

var file_manager_radar_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_manager_radar_proto_goTypes = []any{
	(*Radar)(nil),                          // 0: radar.Radar
	(*RadarResponse)(nil),                  // 1: radar.RadarResponse
	(*RadarsResponse)(nil),                 // 2: radar.RadarsResponse
	(*CreateRadarRequest)(nil),             // 3: radar.CreateRadarRequest
	(*UpdateRadarRequest)(nil),             // 4: radar.UpdateRadarRequest
	(*RecognitionsFilter)(nil),             // 5: radar.RecognitionsFilter
	(*GetTransportObjectInfoRequest)(nil),  // 6: radar.GetTransportObjectInfoRequest
	(*TransportObjectInfo)(nil),            // 7: radar.TransportObjectInfo
	(*GetTransportObjectInfoResponse)(nil), // 8: radar.GetTransportObjectInfoResponse
	(*GetRadarRequest)(nil),                // 9: radar.GetRadarRequest
	(*DeleteRadarRequest)(nil),             // 10: radar.DeleteRadarRequest
	(*TimeZonesResponse)(nil),              // 11: radar.TimeZonesResponse
	(*TimeZone)(nil),                       // 12: radar.TimeZone
	(*RadarModelsResponse)(nil),            // 13: radar.RadarModelsResponse
	(*RadarModel)(nil),                     // 14: radar.RadarModel
	(*Device)(nil),                         // 15: radar.Device
	(*DeviceResponse)(nil),                 // 16: radar.DeviceResponse
	(*UpdateDeviceRequest)(nil),            // 17: radar.UpdateDeviceRequest
	(*ExportTypeParam)(nil),                // 18: radar.ExportTypeParam
	(*ExportType)(nil),                     // 19: radar.ExportType
	(*GetExportTypesResponse)(nil),         // 20: radar.GetExportTypesResponse
	(*ExportStatus)(nil),                   // 21: radar.ExportStatus
	(*GetExportStatusesResponse)(nil),      // 22: radar.GetExportStatusesResponse
	(*Export)(nil),                         // 23: radar.Export
	(*ListExport)(nil),                     // 24: radar.ListExport
	(*ExportEvent)(nil),                    // 25: radar.ExportEvent
	(*ExportsEventsFilter)(nil),            // 26: radar.ExportsEventsFilter
	(*GetExportsEventsRequest)(nil),        // 27: radar.GetExportsEventsRequest
	(*GetExportsEventsResponse)(nil),       // 28: radar.GetExportsEventsResponse
	(*ExportResponse)(nil),                 // 29: radar.ExportResponse
	(*ExportIdResponse)(nil),               // 30: radar.ExportIdResponse
	(*ExportsResponse)(nil),                // 31: radar.ExportsResponse
	(*CreateExportRequest)(nil),            // 32: radar.CreateExportRequest
	(*UpdateExportRequest)(nil),            // 33: radar.UpdateExportRequest
	(*GetExportRequest)(nil),               // 34: radar.GetExportRequest
	(*DeleteExportRequest)(nil),            // 35: radar.DeleteExportRequest
	(*ChangeExportStateRequest)(nil),       // 36: radar.ChangeExportStateRequest
	(*ChangeExportStateResponse)(nil),      // 37: radar.ChangeExportStateResponse
	(*timestamppb.Timestamp)(nil),          // 38: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 39: google.protobuf.Empty
}
var file_manager_radar_proto_depIdxs = []int32{
	0,  // 0: radar.RadarResponse.radar:type_name -> radar.Radar
	0,  // 1: radar.RadarsResponse.radars:type_name -> radar.Radar
	0,  // 2: radar.CreateRadarRequest.radar:type_name -> radar.Radar
	0,  // 3: radar.UpdateRadarRequest.radar:type_name -> radar.Radar
	5,  // 4: radar.GetTransportObjectInfoRequest.filter:type_name -> radar.RecognitionsFilter
	38, // 5: radar.TransportObjectInfo.created_at:type_name -> google.protobuf.Timestamp
	7,  // 6: radar.GetTransportObjectInfoResponse.data:type_name -> radar.TransportObjectInfo
	12, // 7: radar.TimeZonesResponse.time_zones:type_name -> radar.TimeZone
	14, // 8: radar.RadarModelsResponse.models:type_name -> radar.RadarModel
	38, // 9: radar.Device.production_date:type_name -> google.protobuf.Timestamp
	15, // 10: radar.DeviceResponse.device:type_name -> radar.Device
	15, // 11: radar.UpdateDeviceRequest.device:type_name -> radar.Device
	18, // 12: radar.ExportType.parameters:type_name -> radar.ExportTypeParam
	19, // 13: radar.GetExportTypesResponse.types:type_name -> radar.ExportType
	21, // 14: radar.GetExportStatusesResponse.statuses:type_name -> radar.ExportStatus
	26, // 15: radar.GetExportsEventsRequest.filter:type_name -> radar.ExportsEventsFilter
	25, // 16: radar.GetExportsEventsResponse.exportsEvents:type_name -> radar.ExportEvent
	23, // 17: radar.ExportResponse.export:type_name -> radar.Export
	24, // 18: radar.ExportsResponse.exports:type_name -> radar.ListExport
	23, // 19: radar.CreateExportRequest.export:type_name -> radar.Export
	23, // 20: radar.UpdateExportRequest.export:type_name -> radar.Export
	3,  // 21: radar.RadarService.CreateRadar:input_type -> radar.CreateRadarRequest
	4,  // 22: radar.RadarService.UpdateRadar:input_type -> radar.UpdateRadarRequest
	9,  // 23: radar.RadarService.GetRadar:input_type -> radar.GetRadarRequest
	39, // 24: radar.RadarService.GetAllRadars:input_type -> google.protobuf.Empty
	10, // 25: radar.RadarService.DeleteRadar:input_type -> radar.DeleteRadarRequest
	39, // 26: radar.RadarService.GetTimeZones:input_type -> google.protobuf.Empty
	39, // 27: radar.RadarService.GetRadarModels:input_type -> google.protobuf.Empty
	39, // 28: radar.RadarService.GetDevice:input_type -> google.protobuf.Empty
	17, // 29: radar.RadarService.UpdateDevice:input_type -> radar.UpdateDeviceRequest
	6,  // 30: radar.RadarService.GetTransportObjectInfo:input_type -> radar.GetTransportObjectInfoRequest
	39, // 31: radar.RadarService.GetExportsTypes:input_type -> google.protobuf.Empty
	39, // 32: radar.RadarService.GetExportStatuses:input_type -> google.protobuf.Empty
	32, // 33: radar.RadarService.CreateExport:input_type -> radar.CreateExportRequest
	33, // 34: radar.RadarService.UpdateExport:input_type -> radar.UpdateExportRequest
	34, // 35: radar.RadarService.GetExport:input_type -> radar.GetExportRequest
	39, // 36: radar.RadarService.GetAllExports:input_type -> google.protobuf.Empty
	35, // 37: radar.RadarService.DeleteExport:input_type -> radar.DeleteExportRequest
	36, // 38: radar.RadarService.ChangeExportState:input_type -> radar.ChangeExportStateRequest
	27, // 39: radar.RadarService.GetExportEvents:input_type -> radar.GetExportsEventsRequest
	1,  // 40: radar.RadarService.CreateRadar:output_type -> radar.RadarResponse
	1,  // 41: radar.RadarService.UpdateRadar:output_type -> radar.RadarResponse
	1,  // 42: radar.RadarService.GetRadar:output_type -> radar.RadarResponse
	2,  // 43: radar.RadarService.GetAllRadars:output_type -> radar.RadarsResponse
	1,  // 44: radar.RadarService.DeleteRadar:output_type -> radar.RadarResponse
	11, // 45: radar.RadarService.GetTimeZones:output_type -> radar.TimeZonesResponse
	13, // 46: radar.RadarService.GetRadarModels:output_type -> radar.RadarModelsResponse
	16, // 47: radar.RadarService.GetDevice:output_type -> radar.DeviceResponse
	16, // 48: radar.RadarService.UpdateDevice:output_type -> radar.DeviceResponse
	8,  // 49: radar.RadarService.GetTransportObjectInfo:output_type -> radar.GetTransportObjectInfoResponse
	20, // 50: radar.RadarService.GetExportsTypes:output_type -> radar.GetExportTypesResponse
	22, // 51: radar.RadarService.GetExportStatuses:output_type -> radar.GetExportStatusesResponse
	29, // 52: radar.RadarService.CreateExport:output_type -> radar.ExportResponse
	29, // 53: radar.RadarService.UpdateExport:output_type -> radar.ExportResponse
	29, // 54: radar.RadarService.GetExport:output_type -> radar.ExportResponse
	31, // 55: radar.RadarService.GetAllExports:output_type -> radar.ExportsResponse
	30, // 56: radar.RadarService.DeleteExport:output_type -> radar.ExportIdResponse
	37, // 57: radar.RadarService.ChangeExportState:output_type -> radar.ChangeExportStateResponse
	28, // 58: radar.RadarService.GetExportEvents:output_type -> radar.GetExportsEventsResponse
	40, // [40:59] is the sub-list for method output_type
	21, // [21:40] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_manager_radar_proto_init() }
func file_manager_radar_proto_init() {
	if File_manager_radar_proto != nil {
		return
	}
	file_manager_radar_proto_msgTypes[0].OneofWrappers = []any{}
	file_manager_radar_proto_msgTypes[15].OneofWrappers = []any{}
	file_manager_radar_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_radar_proto_rawDesc), len(file_manager_radar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_radar_proto_goTypes,
		DependencyIndexes: file_manager_radar_proto_depIdxs,
		MessageInfos:      file_manager_radar_proto_msgTypes,
	}.Build()
	File_manager_radar_proto = out.File
	file_manager_radar_proto_goTypes = nil
	file_manager_radar_proto_depIdxs = nil
}
