// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: network-service.proto

package proto_radar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_network_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{0}
}

type CurrentNetworkConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	SubnetMask    string                 `protobuf:"bytes,3,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentNetworkConfigResponse) Reset() {
	*x = CurrentNetworkConfigResponse{}
	mi := &file_network_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentNetworkConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentNetworkConfigResponse) ProtoMessage() {}

func (x *CurrentNetworkConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentNetworkConfigResponse.ProtoReflect.Descriptor instead.
func (*CurrentNetworkConfigResponse) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentNetworkConfigResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CurrentNetworkConfigResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CurrentNetworkConfigResponse) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *CurrentNetworkConfigResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // Новый IP-адрес
	SubnetMask    string                 `protobuf:"bytes,3,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"` // Маска подсети
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`                         // Шлюз
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_network_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkConfig) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *NetworkConfig) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkConfig) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *NetworkConfig) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type NetworkConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetMode       int32                  `protobuf:"varint,1,opt,name=set_mode,json=setMode,proto3" json:"set_mode,omitempty"`
	SetIpAddress  string                 `protobuf:"bytes,2,opt,name=set_ip_address,json=setIpAddress,proto3" json:"set_ip_address,omitempty"`    // Новый IP-адрес
	SetSubnetMask string                 `protobuf:"bytes,3,opt,name=set_subnet_mask,json=setSubnetMask,proto3" json:"set_subnet_mask,omitempty"` // Маска подсети
	SetGateway    string                 `protobuf:"bytes,4,opt,name=set_gateway,json=setGateway,proto3" json:"set_gateway,omitempty"`            // Шлюз
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfigResponse) Reset() {
	*x = NetworkConfigResponse{}
	mi := &file_network_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfigResponse) ProtoMessage() {}

func (x *NetworkConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfigResponse.ProtoReflect.Descriptor instead.
func (*NetworkConfigResponse) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConfigResponse) GetSetMode() int32 {
	if x != nil {
		return x.SetMode
	}
	return 0
}

func (x *NetworkConfigResponse) GetSetIpAddress() string {
	if x != nil {
		return x.SetIpAddress
	}
	return ""
}

func (x *NetworkConfigResponse) GetSetSubnetMask() string {
	if x != nil {
		return x.SetSubnetMask
	}
	return ""
}

func (x *NetworkConfigResponse) GetSetGateway() string {
	if x != nil {
		return x.SetGateway
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_network_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TimeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncMode      int32                  `protobuf:"varint,1,opt,name=sync_mode,json=syncMode,proto3" json:"sync_mode,omitempty"`
	NtpServer     string                 `protobuf:"bytes,2,opt,name=ntp_server,json=ntpServer,proto3" json:"ntp_server,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"` // Например "Саратов (UTC+04:00)"
	Datetime      string                 `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"` // Формат "2025-04-01 11:35:00"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_network_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSyncRequest) GetSyncMode() int32 {
	if x != nil {
		return x.SyncMode
	}
	return 0
}

func (x *TimeSyncRequest) GetNtpServer() string {
	if x != nil {
		return x.NtpServer
	}
	return ""
}

func (x *TimeSyncRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *TimeSyncRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTime   string                 `protobuf:"bytes,1,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`      // Формат "2025-04-01 11:35:00"
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`                               // Например "UTC+04:00"
	TimeSyncMode  string                 `protobuf:"bytes,3,opt,name=time_sync_mode,json=timeSyncMode,proto3" json:"time_sync_mode,omitempty"` // "ntp" или "manual"
	NtpServer     string                 `protobuf:"bytes,4,opt,name=ntp_server,json=ntpServer,proto3" json:"ntp_server,omitempty"`            // Текущий NTP сервер (если используется)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_network_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{6}
}

func (x *TimeResponse) GetCurrentTime() string {
	if x != nil {
		return x.CurrentTime
	}
	return ""
}

func (x *TimeResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *TimeResponse) GetTimeSyncMode() string {
	if x != nil {
		return x.TimeSyncMode
	}
	return ""
}

func (x *TimeResponse) GetNtpServer() string {
	if x != nil {
		return x.NtpServer
	}
	return ""
}

type RestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"` // Опционально Задержка перед перезапуском (секунды)
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                  // Отпионально Причина перезапуска (для логирования)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_network_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{7}
}

func (x *RestartRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *RestartRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeepRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"` // Опционально Задержка перед перезапуском (секунды)
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                  // Опционально Причина перезапуска (для логирования)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepRestartRequest) Reset() {
	*x = DeepRestartRequest{}
	mi := &file_network_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepRestartRequest) ProtoMessage() {}

func (x *DeepRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepRestartRequest.ProtoReflect.Descriptor instead.
func (*DeepRestartRequest) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeepRestartRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *DeepRestartRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RestartResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                            // Сообщение о статусе операции
	EstimatedSeconds uint32                 `protobuf:"varint,3,opt,name=estimated_seconds,json=estimatedSeconds,proto3" json:"estimated_seconds,omitempty"` // Оценочное время до завершения перезапуска (секунды)
	ScheduledTime    string                 `protobuf:"bytes,4,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`           // Запланированное время перезапуска (формат "2025-04-01 11:35:00")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_network_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_network_service_proto_rawDescGZIP(), []int{9}
}

func (x *RestartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestartResponse) GetEstimatedSeconds() uint32 {
	if x != nil {
		return x.EstimatedSeconds
	}
	return 0
}

func (x *RestartResponse) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

var File_network_service_proto protoreflect.FileDescriptor

const file_network_service_proto_rawDesc = "" +
	"\n" +
	"\x15network-service.proto\x12\x0enetworkService\"\a\n" +
	"\x05Empty\"\x8c\x01\n" +
	"\x1cCurrentNetworkConfigResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vsubnet_mask\x18\x03 \x01(\tR\n" +
	"subnetMask\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\"}\n" +
	"\rNetworkConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vsubnet_mask\x18\x03 \x01(\tR\n" +
	"subnetMask\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\"\xa1\x01\n" +
	"\x15NetworkConfigResponse\x12\x19\n" +
	"\bset_mode\x18\x01 \x01(\x05R\asetMode\x12$\n" +
	"\x0eset_ip_address\x18\x02 \x01(\tR\fsetIpAddress\x12&\n" +
	"\x0fset_subnet_mask\x18\x03 \x01(\tR\rsetSubnetMask\x12\x1f\n" +
	"\vset_gateway\x18\x04 \x01(\tR\n" +
	"setGateway\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x85\x01\n" +
	"\x0fTimeSyncRequest\x12\x1b\n" +
	"\tsync_mode\x18\x01 \x01(\x05R\bsyncMode\x12\x1d\n" +
	"\n" +
	"ntp_server\x18\x02 \x01(\tR\tntpServer\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x1a\n" +
	"\bdatetime\x18\x04 \x01(\tR\bdatetime\"\x92\x01\n" +
	"\fTimeResponse\x12!\n" +
	"\fcurrent_time\x18\x01 \x01(\tR\vcurrentTime\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12$\n" +
	"\x0etime_sync_mode\x18\x03 \x01(\tR\ftimeSyncMode\x12\x1d\n" +
	"\n" +
	"ntp_server\x18\x04 \x01(\tR\tntpServer\"M\n" +
	"\x0eRestartRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Q\n" +
	"\x12DeepRestartRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x99\x01\n" +
	"\x0fRestartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11estimated_seconds\x18\x03 \x01(\rR\x10estimatedSeconds\x12%\n" +
	"\x0escheduled_time\x18\x04 \x01(\tR\rscheduledTime2\xe2\x04\n" +
	"\x0eNetworkService\x12[\n" +
	"\x13ChangeNetworkConfig\x12\x1d.networkService.NetworkConfig\x1a%.networkService.NetworkConfigResponse\x12^\n" +
	"\x17GetCurrentNetworkConfig\x12\x15.networkService.Empty\x1a,.networkService.CurrentNetworkConfigResponse\x12L\n" +
	"\x0fSetTimeSyncMode\x12\x1f.networkService.TimeSyncRequest\x1a\x18.networkService.Response\x12E\n" +
	"\x0eGetCurrentTime\x12\x15.networkService.Empty\x1a\x1c.networkService.TimeResponse\x12R\n" +
	"\x0fRestartServices\x12\x1e.networkService.RestartRequest\x1a\x1f.networkService.RestartResponse\x12P\n" +
	"\rRestartDevice\x12\x1e.networkService.RestartRequest\x1a\x1f.networkService.RestartResponse\x12X\n" +
	"\x11DeepRestartDevice\x12\".networkService.DeepRestartRequest\x1a\x1f.networkService.RestartResponseB!Z\x1fgl.npo-its.ru/radar/proto-radarb\x06proto3"

var (
	file_network_service_proto_rawDescOnce sync.Once
	file_network_service_proto_rawDescData []byte
)

func file_network_service_proto_rawDescGZIP() []byte {
	file_network_service_proto_rawDescOnce.Do(func() {
		file_network_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_service_proto_rawDesc), len(file_network_service_proto_rawDesc)))
	})
	return file_network_service_proto_rawDescData
}

var file_network_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_network_service_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: networkService.Empty
	(*CurrentNetworkConfigResponse)(nil), // 1: networkService.CurrentNetworkConfigResponse
	(*NetworkConfig)(nil),                // 2: networkService.NetworkConfig
	(*NetworkConfigResponse)(nil),        // 3: networkService.NetworkConfigResponse
	(*Response)(nil),                     // 4: networkService.Response
	(*TimeSyncRequest)(nil),              // 5: networkService.TimeSyncRequest
	(*TimeResponse)(nil),                 // 6: networkService.TimeResponse
	(*RestartRequest)(nil),               // 7: networkService.RestartRequest
	(*DeepRestartRequest)(nil),           // 8: networkService.DeepRestartRequest
	(*RestartResponse)(nil),              // 9: networkService.RestartResponse
}
var file_network_service_proto_depIdxs = []int32{
	2, // 0: networkService.NetworkService.ChangeNetworkConfig:input_type -> networkService.NetworkConfig
	0, // 1: networkService.NetworkService.GetCurrentNetworkConfig:input_type -> networkService.Empty
	5, // 2: networkService.NetworkService.SetTimeSyncMode:input_type -> networkService.TimeSyncRequest
	0, // 3: networkService.NetworkService.GetCurrentTime:input_type -> networkService.Empty
	7, // 4: networkService.NetworkService.RestartServices:input_type -> networkService.RestartRequest
	7, // 5: networkService.NetworkService.RestartDevice:input_type -> networkService.RestartRequest
	8, // 6: networkService.NetworkService.DeepRestartDevice:input_type -> networkService.DeepRestartRequest
	3, // 7: networkService.NetworkService.ChangeNetworkConfig:output_type -> networkService.NetworkConfigResponse
	1, // 8: networkService.NetworkService.GetCurrentNetworkConfig:output_type -> networkService.CurrentNetworkConfigResponse
	4, // 9: networkService.NetworkService.SetTimeSyncMode:output_type -> networkService.Response
	6, // 10: networkService.NetworkService.GetCurrentTime:output_type -> networkService.TimeResponse
	9, // 11: networkService.NetworkService.RestartServices:output_type -> networkService.RestartResponse
	9, // 12: networkService.NetworkService.RestartDevice:output_type -> networkService.RestartResponse
	9, // 13: networkService.NetworkService.DeepRestartDevice:output_type -> networkService.RestartResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_service_proto_init() }
func file_network_service_proto_init() {
	if File_network_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_service_proto_rawDesc), len(file_network_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_service_proto_goTypes,
		DependencyIndexes: file_network_service_proto_depIdxs,
		MessageInfos:      file_network_service_proto_msgTypes,
	}.Build()
	File_network_service_proto = out.File
	file_network_service_proto_goTypes = nil
	file_network_service_proto_depIdxs = nil
}
